wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    code_path: code/image_captioning_with_keras8.ipynb
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.4
    session_history: code/_session_history.ipynb
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 30
hidden_layer_size:
  desc: null
  value: 3
